### ISSUE TITLE
Incorrect version number

### ISSUE THREAD

**Issue by Hieromon** [gilmaimon/ArduBadge#11]
Thank you for providing a useful notification service.

Badge version notation of my library as [PageBuilder](https://github.com/Hieromon/PageBuilder) is not updated since `1.2.3`:

![image28](https://user-images.githubusercontent.com/12591771/60272736-a9099180-992f-11e9-8fd9-80fba8fcb973.png)

But the [ArduBadge page of the PageBuilder](https://www.ardu-badge.com/PageBuilder) is correct, it displays as `1.3.4`:

![PageBuilder](https://user-images.githubusercontent.com/12591771/60272436-208af100-992f-11e9-8d0c-ca13ed38d968.png)

The link of ArduBdge placed in readme.md of PageBuilder is as follows:
```
[![arduino-library-badge](https://www.ardu-badge.com/badge/PageBuilder.svg)](https://www.ardu-badge.com/PageBuilder)
```
Please let me know how to fix it.

**Comment by gilmaimon** [comment]
Hi, thank you for opening an issue!

What happens is that GitHub caches the image instead of making a request to ArduBadge for each visit. You can ask it to not cache images by adding a question mark to the badge's URL.

Try replacing your current badge with this code:
```
[![arduino-library-badge](https://www.ardu-badge.com/badge/PageBuilder.svg?)](https://www.ardu-badge.com/PageBuilder)
```

This should fix it :smile:

Best regards, 
Gil.

**Comment by Hieromon** [comment]
It solved!, Thank you for a quick response.

**Comment by Hieromon** [comment]
Hello Gil,

I have the same phenomenon as the problem solved last time.
It is now occurring in the [AutoConnect](https://github.com/Hieromon/AutoConnect) repository.
I checked the URL of the badge, but the previous solution has already been applied as shown below.
```
[![arduino-library-badge](https://www.ardu-badge.com/badge/AutoConnect.svg?)](https://www.ardu-badge.com/AutoConnect)
```
Could you lead me to a solution?

Best Regards,
Hieromon

**Comment by gilmaimon** [comment]
This is a bug, I'm on it.

**Comment by gilmaimon** [comment]
Fixed! Please make sure you can see it behaves as you expect.

Thank you for reporting the issue.

Have a great day,
Gil.

**Comment by Hieromon** [comment]
I confirmed it solved.
Thank you for always taking action quickly.
