### ISSUE TITLE
PioBadge ?

### ISSUE THREAD

**Issue by tobozo** [gilmaimon/ArduBadge#22]
Hey and thanks for the awesome bagde generator I'm using on a few projects.

As a library maintainter I can see that sometimes library versions propagate differently depending on the registry, and was wondering if there was such a thing as platformio-badges ?

**Comment by bblanchon** [comment]
PlatformIO added it recently: [![ArduinoJson](https://badges.registry.platformio.org/packages/bblanchon/library/ArduinoJson.svg)](https://registry.platformio.org/packages/libraries/bblanchon/ArduinoJson)

**Comment by tobozo** [comment]
yay !

thanks for the tip @bblanchon 

closing the issue
