### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by tobozo** [gilmaimon/ArduBadge#24]
Hey and thanks for your awesome badge system :+1: 

The badges are currently broken, something went wrong with the ACME client maybe?

    The certificate for www.ardu-badge.com expired on 21/09/2022.

![image](https://user-images.githubusercontent.com/1893754/192479537-e9cfcfe0-f480-403e-9b4a-30eaedbf05f3.png)

**Comment by berrak** [comment]
The server certificate expired 6 days ago. I guess it's just a matter to fix that.

**Comment by gilmaimon** [comment]
> The server certificate expired six days ago. So I guess it's just a matter to fix that.

Yup

Fixed it, thank you.
