### ISSUE TITLE
Version of badge does not update

### ISSUE THREAD

**Issue by cyijun** [gilmaimon/ArduBadge#28]
Hi, the badge of my library does not update, please help

https://www.arduino.cc/reference/en/libraries/esp32mqttclient/

https://github.com/cyijun/ESP32MQTTClient

**Comment by RobertByrnes** [comment]
Hi, I am experiencing the same issue: [![arduino-library-badge](https://www.ardu-badge.com/badge/GovoroxSSLClient.svg)](https://www.ardu-badge.com/badge/GovoroxSSLClient.svg) This badge is not updating. The repo is hosted at

https://github.com/govorox/SSLClient

https://www.arduinolibraries.info/libraries/govorox-ssl-client

**Comment by 0015** [comment]
Hi, I am also having a problem that Ardu Badge's version is not updated. 
https://github.com/0015/ChatGPT_Client_For_Arduino
It should be v0.2.0

**Comment by askuric** [comment]
Our library too :
[https://www.ardu-badge.com/badge/Simple FOC.svg](https://www.ardu-badge.com/badge/Simple%20FOC.svg).

It should be 2.3.3 and in the badge its 2.3.2

**Comment by NuclearPhoenixx** [comment]
I'm sure this is a general issue and not specific to individual projects. ArduBadge looks to be abandoned if you ask me.

**Comment by dmadison** [comment]
Yep, not updating for me either. That's a shame, this was a really useful tool.

**Comment by gilmaimon** [comment]
Hi guys! Sorry for the very delayed comment and downtime.

This project is not being actively maintained / developed but I honestly had no idea it is used by so many people (or useful to any) 

I've updated the download URL to use https, and restarted the server - it seems to work now. I might consider a re-write to avoid such things from happening in the future. Thank you for opening an issue and using this tool :)

Let me know if the issue persists.

Gil.

**Comment by dmadison** [comment]
Thanks for following up, Gil. I've checked a few of my repositories with the badge. It appears that restarting the server may have cleared the cached badge images, but after clicking-through to the library page they are regenerated and everything seems to be in order. The badges are now up to date with the latest versions and everything is as it should be.

I have the badge on a half dozen or so libraries, it's a nice little badge and I'm sure more than a few users have found the library installation instructions helpful. Thank you for your hard work!

**Comment by askuric** [comment]
Just wanned to say that I completely agree with @dmadison. Thanks for making and maintaining this repo!
