### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by TomasRoj** [gilmaimon/ArduBadge#7]
Hey,

In Readme is written that this section will help you with contribution. But there are no instructions. Can I make them?

**Comment by gilmaimon** [comment]
Hi,
The section does have some instructions on running the project locally so you can try chaning things - but the instructions are actually out-dated and the section indeed lacks alot of information. 
Of course you could make them! it will be very helpfull. I will be glad to help with any queshtions you have while doing that.

Thank you.

**Comment by TomasRoj** [comment]
Ok. I will look at that in the evening when I will have laptop with me. I will leave this issue opened for future questions. For hundred percents I will do that!

**Comment by TomasRoj** [comment]
Ok I created first pull request now. Check it out

**Comment by gilmaimon** [comment]
Merged 😄 
Thank you.
