### ISSUE TITLE
Server - question

### ISSUE THREAD

**Issue by TomasRoj** [gilmaimon/ArduBadge#9]
Hey,

I wan to use you library on my library. But you say that i need to install some software on it. What server you mean? I dont undersand this at all.

**Comment by gilmaimon** [comment]
Hi, it is really simple, I will help you:
1. First, go to the [website](https://www.ardu-badge.com/)
2. Go to the `Go Badge Yourself` section
3. Edit the example, replace `MyLibrary` with your own library name (for example, I see you have a library named `BasicsLibrary`)
4. Then, Just copy the markdown generated below and use it on your readme! 

It will look like this:
[![arduino-library-badge](https://www.ardu-badge.com/badge/BasicsLibrary.svg?)](https://www.ardu-badge.com/BasicsLibrary)

Markdown Code:
`[![arduino-library-badge](https://www.ardu-badge.com/badge/BasicsLibrary.svg?)](https://www.ardu-badge.com/BasicsLibrary)`

Thats it 😃

**Comment by TomasRoj** [comment]
yes, yes. I tought about it one more time and I have it thanks. Maybe i will make another pr that there will not be theese issues any more 😂. I must say that its fun to contribute with you and I am making library for beginners. Its availibe on my github. Second version doesnt work at all so I was looking if someone can help me. What do you think?

**Comment by gilmaimon** [comment]
I'm glad, I am also very happy when others contribute and I am happy to help and contribute myself.
Recently I've been pretty busy, but I am still happy to help with more spceific issues and problems. 

My Email is mail.gilmaimon@gmail.com, let me know if you need any help 👍

**Comment by TomasRoj** [comment]
okay I will save that for later use ✌👏. Thank you too. PS: I created problably last pr in this repo look at it.
Best regards,
Tom
